# Numpy
Numerical Python

### **How to install Numpy**

In [ ]:
pip install numpy

**Install Numpy**

In [ ]:
import numpy as NP

**Creat 1D array**

In [ ]:
A = NP.array([1,2,3])
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


**2D Array**

In [ ]:
A = NP.array([[1,2,3],[10,20,30]])
print(A)
print(type(A))

[[ 1  2  3]
 [10 20 30]]
<class 'numpy.ndarray'>


In [ ]:
NP.zeros((2,3))  # 2 Rows and 3 coloum

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
NP.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
NP.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
NP.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
NP.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
NP.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
NP.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
NP.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
NP.indices((4,4))

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [ ]:
NP.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
A = NP.array([1,2,3])
print(A)
print(A.dtype)
print(type(A))

[1 2 3]
int64
<class 'numpy.ndarray'>


**Difference Between Numpy and List**

In [ ]:
import numpy as NP

# List
L = range(1000)

import sys

A =1

print(sys.getsizeof(A))  # To know memory allocated to A
print("List Size - ",sys.getsizeof(A)* len(L))

# Numpy
N = NP.arange(1000)
print("Numpy Size - ",N.size * N.itemsize)

28
List Size -  28000
Numpy Size -  8000


**Numpy Operations**

In [ ]:
A =NP.array([[1,2,3],[10,20,30]])
print(A)
print(A.ndim)  #ndim -->  Number  of Dimentions
print(A.itemsize)  # itemsize is use to know the size of rray
print(A.size)  # Size Function is used to know the Size of the Array

[[ 1  2  3]
 [10 20 30]]
2
8
6


#### **Rehape** 
When u want to change the number of Rows and Column

In [ ]:
import numpy as NP
B = NP.array([[1,2,3],[10,20,30]])
print(B)

[[ 1  2  3]
 [10 20 30]]


In [ ]:
B.reshape(3,2)

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

### **Slicing**

In [ ]:
B

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
B[0,0]

1

In [ ]:
B[0,1]

2

In [ ]:
B[1,1]

20

In [ ]:
B[1,2]

30

In [ ]:
B[0:,1]

array([ 2, 20])

In [ ]:
B[1:,2:]

array([[30]])

In [ ]:
B[0:2,0:1]

array([[ 1],
       [10]])

In [ ]:
C = NP.array([[1,2,3,4,5],[10,20,30,40,50]])
C

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [ ]:
C.shape

(2, 5)

In [ ]:
C[0:3,0:3]

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
C[0:2,4:5]

array([[ 5],
       [50]])

In [ ]:
C[0:2,2:5]

array([[ 3,  4,  5],
       [30, 40, 50]])

In [ ]:
C[[1,1,1],[0,2,4]]

array([10, 30, 50])

In [ ]:
C.min()

1

In [ ]:
C.max()

50

In [ ]:
C.sum()

165

In [ ]:
# Sum according to column wise
print(C)
print("After sum")
print(NP.sum(C, axis=0))

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
After sum
[11 22 33 44 55]


In [ ]:
# Sum according to Row wisse
print(C)
print("After Sum ")
print(NP.sum(C, axis= 1))

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
After Sum 
[ 15 150]


**Array Mathametical Operations**

In [ ]:
X =NP.array([[1,2],[3,4]])
Y =NP.array([[5,6],[7,8]])

print(X)
print(Y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(X+Y)

# OR

print(NP.add(X,Y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(X-Y)

# OR

print(NP.subtract(X,Y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print(X*Y)

# OR

print(NP.multiply(X,Y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
print(X/Y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(NP.sqrt(X))  

[[1.         1.41421356]
 [1.73205081 2.        ]]


-----------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
# ID Array
A1 = NP.arange(6)
A1

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Coverted to 2D array
print(A1.reshape(3,2))

print("OR")

print(NP.reshape(A1,(2,3)))

[[0 1]
 [2 3]
 [4 5]]
OR
[[0 1 2]
 [3 4 5]]


In [ ]:
# Covert 2D array into 1D array
print(NP.reshape(A1,(6)))

print("OR")

# By using flatten 
print(A1.flatten())

[0 1 2 3 4 5]
OR
[0 1 2 3 4 5]
